GET http://localhost:3000/cursos

###

POST http://localhost:3000/cursos HTTP/1.1
Content-Type: application/json

{
    "curso": "JS Pristine"
}

###

PUT http://localhost:3000/cursos/2 HTTP/1.1
Content-Type: application/json

{
    "curso": "Angular Material"
}

###

DELETE http://localhost:3000/cursos